name = "corpora-ai"
main = "src/index.js"
compatibility_date = "2026-09-01"
account_id = "586f298a211c493ff5633233b09c9cd5"
workers_dev = true

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "blog_db"
database_id = "038c5843-0c9d-43ea-8347-b8840768b95d"
